project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    embed-resources: true
    comments:
      hypothesis: true
  docx: default
  plos-pdf: default

execute:
  freeze: true
